language: python
python:
  - "2.6"
  - "2.7"
matrix:
  include:
    - python: "2.7"
      env: COVERAGE=true

install:
  - pip install tox
script:
  - if [ -z "$COVERAGE" ]; then tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/'); fi
  - if [ ! -z "$COVERAGE" ]; then tox -e coverage; fi